FROM --platform=$BUILDPLATFORM cgr.dev/chainguard/dotnet-sdk:latest@sha256:3b85ed71b772accd27035860b7c65b18bdc93c12b05c974c494eee361a632f83 AS build

ARG TARGETARCH="amd64"
ARG BASE="ScaffoldProjectName"
ARG TARGETPROJECT="ScaffoldProjectName.ApiService"

WORKDIR /src

COPY --chown=65532:65532 "src/$BASE.ServiceDefaults" ./src/$BASE.ServiceDefaults/
COPY --chown=65532:65532 "src/$TARGETPROJECT" ./src/$TARGETPROJECT/
COPY --chown=65532:65532 Directory.Build.props ./
COPY --chown=65532:65532 Directory.Build.targets ./
COPY --chown=65532:65532 Directory.Packages.props ./
COPY --chown=65532:65532 *.slnx ./
COPY --chown=65532:65532 global.json ./
COPY --chown=65532:65532 nuget.config ./

RUN --mount=type=cache,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/v3-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugins-cache \
    --mount=type=cache,target=/tmp/NuGetScratchroot \
    dotnet restore -a $TARGETARCH "src/$TARGETPROJECT/$TARGETPROJECT.csproj"


RUN --mount=type=cache,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/v3-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugins-cache \
    --mount=type=cache,target=/tmp/NuGetScratchroot \
    dotnet publish "src/$TARGETPROJECT/$TARGETPROJECT.csproj" \
    --no-restore \
    --configuration Release \
    --output dist/publish

# Final stage
FROM cgr.dev/chainguard/aspnet-runtime:latest@sha256:b025e94d1f5f6c060e706af57ad258da187bbe412b2a03a720dcaf8c6cffec8b AS final

WORKDIR /app

COPY --from=build /src/dist/publish .

ENV DOTNET_RUNNING_IN_CONTAINER=true \
    DOTNET_EnableDiagnostics=0 \
    HTTP_PORT=8080 \
    ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "ScaffoldProjectName.ApiService.dll"]
