issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:ScaffoldOwner/ScaffoldTemplate:ref:refs/heads/(main|master|develop)"
claim_pattern:
  workflow_ref: "ScaffoldOwner/ScaffoldTemplate/\\.github/workflows/svg-optimization\\.yml@refs/heads/(main|master|develop)"
permissions:
  contents: write
  id-token: write
