name: Verify GitHub Actions integrity
on:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  verify-actions:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
#if (harden-runner)
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
          disable-telemetry: "true"
          disable-sudo-and-containers: "true"
#endif
      - name: Optimize Git config for CI
        run: |
          # Disable compression for faster network transfer.
          git config --global core.compression 0
          # Turn off fsync
          git config --global core.fsync -all
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref || github.ref_name }} # checkout the PR branch or the default branch
          persist-credentials: false
          sparse-checkout: |
            .github
          filter: "blob:none"
      - uses: gjtorikian/gh-actions-lockfile@8abbeb1fe0a4bf20279c81fa206e6a2fc862a830 # v1.2.1
        with:
          mode: verify
          comment: false
          skip-advisories: true # NOT recommended but otherwise it would force too much rebasing on PRs due to harden-runner setup
          workflows: ".github/workflows"
          output: ".github/actions.lock.json"

  update-lockfile:
    needs: verify-actions
    if: failure()
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # to write lockfile back
    steps:
#if (harden-runner)
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
          disable-telemetry: "true"
          disable-sudo-and-containers: "true"
#endif
      - name: Optimize Git config for CI
        run: |
          # Disable compression for faster network transfer.
          git config --global core.compression 0
          # Turn off fsync
          git config --global core.fsync -all
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }} # checkout the PR branch so commits land on the PR
          persist-credentials: true # so it can push back the lockfile
          sparse-checkout: |
            .github
          filter: "blob:none"
      - uses: gjtorikian/gh-actions-lockfile@8abbeb1fe0a4bf20279c81fa206e6a2fc862a830 # v1.2.1
        with:
          mode: generate
          require-sha: true
          workflows: ".github/workflows"
          output: ".github/actions.lock.json"
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore(ci): update actions lockfile"
          file_pattern: ".github/actions.lock.json"
